

package MernisServiceReference;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 40BC9FD709EF236FB1335F089E282C654181D3F9674DF6FDF7EF1FEBC5D9345665F68F73E0B32B13C597DEEEBC577E6300D73E5710FD3DE5C503390FD8D1CFB0
//------------------------------------------------------------------------

public class QTGSoapException extends java.lang.Exception
{
    private org.w3c.dom.Element _details=null;
    private Object _fault = null;
    
    public QTGSoapException(String message,org.w3c.dom.Element details)
    {
        super(message);
        _details=details;
    }

    public QTGSoapException(Object fault)
    {
        _fault=fault;
    }

    public Object getFault() {
        return _fault;
    }


    public org.w3c.dom.Element getDetails() {
        return _details;
    }
}